[input]
description = "label 'b' and '\"b' with escaped quote to trick naive string comparison"
is_compressed = false

[input.source]
json_string = '''
{
    "a": {
        "\"b": 42,
        "b": 43 
    }
}
'''

[[queries]]
query = "$..b"
description = "descendant search for 'b'"

[queries.results]
count = 1
spans = [[45, 47]]
nodes = ["43"]

[[queries]]
query = """$..['"b']"""
description = "descendant search for 'b' with a leading quote"

[queries.results]
count = 1
spans = [[28, 30]]
nodes = ["42"]