[input]
description = "object with two labels, 'x' and 'x' with a preceding escaped double quote"
is_compressed = false

[input.source]
json_string = '''
{
    "\"x": 42,
    "x": 17
}
'''

[[queries]]
query = "$['x']"
description = "select 'x' directly"

[queries.results]
count = 1
spans = [[26, 28]]
nodes = ["17"]

[[queries]]
query = """$['"x']"""
description = "select 'x' with quote directly"

[queries.results]
count = 1
spans = [[13, 15]]
nodes = ["42"]