pub const TWITTER_MINI: &str = ".a_lut_tests/test_data/MB_1/twitter_(767kB).json";

pub const TWITTER_SHORT: &str = ".a_lut_tests/test_data/MB_100/twitter_short_(80MB).json";
pub const BESTBUY_SHORT: &str = ".a_lut_tests/test_data/MB_100/bestbuy_short_(103MB).json";
pub const GOOGLE_SHORT: &str = ".a_lut_tests/test_data/MB_100/google_map_short_(107MB).json";
pub const WALMART_SHORT: &str = ".a_lut_tests/test_data/MB_100/walmart_short_(95MB).json";

pub const BESTBUY: &str = ".a_lut_tests/test_data/GB_1/bestbuy_large_record_(1GB).json";
pub const WALMART: &str = ".a_lut_tests/test_data/GB_1/walmart_large_record_(995MB).json";
pub const TWITTER: &str = ".a_lut_tests/test_data/GB_1/twitter_large_record_(843MB).json";
pub const GOOGLE: &str = ".a_lut_tests/test_data/GB_1/google_map_large_record_(1.1GB).json";

// google_map_large
pub const TEST_GOOGLE: (&str, &[(&str, &str)]) = (
    GOOGLE,
    &[
        // ("0", "$[*]..bounds"),
        // ("1", "$[*]..bounds.northeast"),
        // ("2", "$[*]..bounds.northeast.lat"),
        // ("3", "$[*]..bounds.northeast.lng"),
        // ("4", "$[*]..copyrights"),
        // ("5", "$[*]..summary"),
        // ("6", "$[*]..warnings"),
        // ("7", "$[*]..waypoint_order"),
        // ("8", "$[*].routes[*]"),
        // ("9", "$[*].routes[*]..legs"),
        // ("10", "$[*].routes[*]..points"),
        // ("11", "$[*].routes[*]..steps[*]"),
        // ("12", "$[*].routes[*].bounds"),
        // ("13", "$[*].routes[*].bounds.northeast"),
        // ("14", "$[*].routes[*].bounds.northeast.lat"),
        // ("15", "$[*].routes[*].bounds.northeast.lng"),
        // ("16", "$[*].routes[*].legs[*].start_location.lat"),
        // ("17", "$[*].routes[*].legs[*].steps[1]"),
        // ("18", "$[*].routes[*].legs[*].steps[1].distance.text"),
        // ("19", "$[*].routes[*].legs[*].traffic_speed_entry"),
        // ("20", "$[*].routes[*].overview_polyline"),
        // ("21", "$[*].routes[*].overview_polyline.points"),
        // ("22", "$[*].routes[*].summary"),
        // ("23", "$[*].routes[*].warnings"),
        // ("24", "$[*].routes[*].waypoint_order"),
        // ("25", "$[1]"),
        // ("26", "$[10].routes[*].bounds"),
        // ("27", "$[100].routes[*].bounds"),
        // ("28", "$[1000].routes[*].bounds"),
        // ("29", "$[2000].routes[*].bounds"),
        // ("30", "$[3000].routes[*].bounds"),

        // ("100", "$[*].routes[*].legs[*]"),
        // ("101", "$[*].routes[*].legs[*].steps[*]"),
        // ("102", "$[*].routes[*].legs[*].steps[*].distance"),
        // ("103", "$[*].routes[*].legs[*].steps[*].distance.text"),
        // ("104", "$[*].routes[*].legs[*].steps[*].distance.value"),
        // ("108", "$[*].routes[*].legs[*].steps[*].duration"),
        // ("109", "$[*].routes[*].legs[*].steps[*].polyline"),
        // ("110", "$[*].routes[*].legs[*].steps[*].polyline.points"),
        // ("111", "$[*].routes[*].legs[*].steps[*].end_location"),
        // ("112", "$[*].routes[*].legs[*].steps[*].html_instructions"),
        // ("113", "$[*].routes[*].legs[*].steps[*].travel_mode"),
        // ("114", "$[*].routes[*].legs[*].steps[*].start_location"),
        // ("115", "$[*].routes[*].legs[*].steps[*].start_location.lat"),
        // ("116", "$[*].routes[*].legs[*].steps[*].start_location.lng"),
        // ("117", "$[*].routes[*].legs[*].steps[*].maneuver"),
        // ("118", "$[*].routes[*].legs[*]..lat"),
        // ("119", "$[*].routes[*].legs[*]..lng"),
        ("200", "$[*].available_travel_modes"),
        ("201", "$[*].copyrights"),
        ("202", "$[*].routes[*]"),
        ("203", "$[*].routes[*].legs[*]"),
        ("204", "$[4000].routes[*].bounds"),
        ("205", "$[*].routes[1]"),
    ],
);

pub const TEST_BESTBUY: (&str, &[(&str, &str)]) = (
    BESTBUY,
    &[
        ("100", "$.products[5].videoChapters"),
        ("101", "$.products[*].videoChapters"),
        ("102", "$.products[*].videoChapters[1].chapter"),
        ("103", "$.products[*].shipping[*]"),
        ("104", "$.products[*].shipping[*].ground"),
        ("105", "$.products[*].shipping[*].nextDay"),
        ("106", "$.products[*].shipping[*].secondDay"),
        ("107", "$.products[*].shipping[*].vendorDelivery"),
        ("108", "$.products[*].shippingLevelsOfService[*]"),
        ("109", "$.products[*].shippingLevelsOfService[*].serviceLevelId"),
        ("110", "$.products[*].shippingLevelsOfService[*].serviceLevelName"),
        ("111", "$.products[*].shippingLevelsOfService[*].unitShippingPrice"),
        ("112", "$.products[*].categoryPath[2]"),
        ("113", "$.products[*].categoryPath[*].id"),
        ("114", "$.products[*].categoryPath[*].name"),
        ("115", "$.products[*].quantityLimit"),
        ("116", "$.products[*].earlyTerminationFees[*]"),
        ("117", "$.products[*].frequentlyPurchasedWith[*]"),
        ("118", "$.products[*].includedItemList[*]"),
        ("119", "$.products[*].accessories[*]"),
        ("120", "$.products[*].planFeatures[*]"),
        ("121", "$.products[*].homeDelivery"),
        ("122", "$.products[*].carrierPlans[*]"),
        ("123", "$.products[*].freeShipping"),
        ("124", "$.products[*].additionalFeatures[*]"),
        ("125", "$.products[*].additionalFeatures[*].feature"),
        ("126", "$.products[*].dollarSavings"),
        ("127", "$.products[*].lengthInMinutes"),
        ("128", "$.products[*].screenFormat"),
    ],
);

pub const TEST_TWITTER: (&str, &[(&str, &str)]) = (
    TWITTER,
    &[
        // ("100", "$[*].geo"),
        // ("101", "$[*].id"),
        // ("102", "$[*].source"),
        // ("103", "$[*].timestamp_ms"),
        // ("104", "$[*].user.created_at"),
        // ("105", "$[*].user.followers_count"),
        // ("106", "$[*].user.lang"),
        // ("107", "$[*].user.listed_count"),
        // ("108", "$[*].user.profile_image_url_https"),
        // ("109", "$[*].user.profile_sidebar_border_color"),
        // ("110", "$[*].user.screen_name"),
        // ("111", "$[*].user.verified"),
        // ("112", "$[*].retweeted_status.id"),
        // ("113", "$[*].retweeted_status.filter_level"),
        // ("114", "$[*].retweeted_status.user.following"),
        // ("115", "$[*].retweeted_status.user.name"),
        // ("116", "$[*].retweeted_status[*]"),
        // ("117", "$[*].retweeted_status[*]..entities..url"),
        // ("118", "$[*].retweeted_status[*]..entities.symbols[*]"),
        // ("119", "$[*].retweeted_status[*]..entities.user_mentions[*]"),
        // ("120", "$[*].retweeted_status[*]..id"),
        // ("121", "$[*].retweeted_status[*]..in_reply_to_screen_name"),
        // ("122", "$[*].retweeted_status[*].user.lang"),
        // ("123", "$[*].entities.hashtags[*]"),
        // ("124", "$[*].entities.symbols[*]"),
        // ("125", "$[*].entities.symbols[1]"),
        // ("126", "$[*].entities.urls[*].display_url"),
        // ("127", "$[*].entities..symbols[*]"),
        // ("128", "$[*].entities..url"),
        // ("129", "$[*]..id"),
        ("200", "$[*].entities..symbols[*]"),
        ("201", "$[*].entities..url"),
        ("202", "$[*].entities.symbols[*]"),
        ("203", "$[*].entities.symbols[1]"),
        ("204", "$[*].entities.urls[*].display_url"),
        ("205", "$[*].timestamp_ms"),
    ],
);
// const TEST_DATA: &[(&str, &str, &str, &str)] = &[
//     ("Twitter b0", TWITTER_JSON, "$.search_metadata.count"),

//     ("Twitter y0", TWITTER_JSON, "$.search_metadata.count"),
// ];
